language: go
go:
- 1.10.x

before_install:
- go get -u github.com/golang/dep/cmd/dep

script:
- dep ensure
- make

before_deploy:
- sha256sum kube-oidc kube-oidc.exe > SHASUMS256.txt

deploy:
  provider: releases
  api_key:
    secure: TODO
  file:
  - kube-oidc
  - kube-oidc.exe
  - SHASUMS256.txt
  skip_cleanup: true
  on:
    repo: mobiliar/kube-oidc
    tags: true
